export const NEON_COLORS = [
  { color: "text-neon-blue", hex: "#00f3ff", neonClass: "neon-text-blue" },
  { color: "text-neon-pink", hex: "#ff00ff", neonClass: "neon-text-pink" },
  { color: "text-neon-green", hex: "#00ff00", neonClass: "neon-text-green" },
  { color: "text-neon-yellow", hex: "#fff700", neonClass: "neon-text-yellow" },
  { color: "text-neon-royal", hex: "#4d4dff", neonClass: "neon-text-royal" },
  { color: "text-neon-coral", hex: "#ff4d4d", neonClass: "neon-text-coral" },
  { color: "text-neon-purple", hex: "#bc13fe", neonClass: "neon-text-purple" },
];

export const getRandomNeonColor = () =>
  NEON_COLORS[Math.floor(Math.random() * NEON_COLORS.length)];

export const TOYS = [
  {
    id: 1,
    slug: "slave-duck",
    title: "SLAVE",
    subtitle: "DUCK",
    info: "whatever you say, sir",
    color: "text-neon-blue",
    neonClass: "neon-text-blue",
    coverImage: "/images/slaveduck-cover.webp",
    galleryImages: [
      "/images/slaveduck-1.webp",
      "/images/slaveduck-2.webp",
      "/images/slaveduck-3.webp",
      "/images/slaveduck-4.webp",
    ],
    description:
      "A fusion of traditional Japanese aesthetics and high-tech materials. Cyber Mochi features a translucent shell with internal fiber-optic lighting that pulses with a rhythmic glow.",
    year: "2023",
    material: "Resin",
    collection: "DESIGNER TOYS",
  },
  {
    id: 2,
    slug: "thekiss",
    title: "THE",
    subtitle: "KISS",
    info: "feel it on your cheek...",
    color: "text-neon-pink",
    neonClass: "neon-text-pink",
    coverImage: "/images/kiss-1.webp",
    galleryImages: [
      "/images/kiss-1.webp",
      "/images/kiss-2.webp",
      "/images/kiss-3.webp",
      "/images/kiss-4.webp",
      "/images/kiss-5.webp",
      "/images/kiss-6.webp",
      "/images/kiss-7.webp",
    ],
    description:
      "The Neon Ghost haunts the urban landscape. Crafted from a proprietary phosphorescent polymer, it absorbs light during the day and emits a haunting pink radiance in total darkness.",
    year: "2023",
    material: "Resin",
    collection: "DESIGNER TOYS",
  },
  {
    id: 3,
    slug: "zureyder",
    title: "ZÜREYDER",
    subtitle: " ",
    info: "an imagnary friend to the earth",
    color: "text-neon-pink",
    neonClass: "neon-text-pink",
    coverImage: "/images/zureyder-cover.webp",
    galleryImages: [
      "/images/zureyder-1.webp",
      "/images/zureyder-2.webp",
      "/images/zureyder-3.webp",
      "/images/zureyder-4.webp",
      "/images/zureyder-5.webp",
      "/images/zureyder-6.webp",
    ],
    description:
      "The Neon Ghost haunts the urban landscape. Crafted from a proprietary phosphorescent polymer, it absorbs light during the day and emits a haunting pink radiance in total darkness.",
    year: "2024",
    material: "Resin",
    collection: "DESIGNER TOYS",
  },
  {
    id: 4,
    slug: "mr-giraffe",
    title: "MISTER",
    subtitle: "GIRAFFE",
    info: "have a nice daaaay!",
    color: "text-neon-pink",
    neonClass: "neon-text-pink",
    coverImage: "/images/mrgiraffe-cover.webp",
    galleryImages: [
      "/images/mrgiraffe-1.webp",
      "/images/mrgiraffe-2.webp",
      "/images/mrgiraffe-3.webp",
      "/images/mrgiraffe-4.webp",
      "/images/mrgiraffe-5.webp",
      "/images/mrgiraffe-6.webp",
    ],
    description:
      "The Neon Ghost haunts the urban landscape. Crafted from a proprietary phosphorescent polymer, it absorbs light during the day and emits a haunting pink radiance in total darkness.",
    year: "2024",
    material: "Resin",
    collection: "DESIGNER TOYS",
  },
  {
    id: 5,
    slug: "sneaky-snake",
    title: "SNEAKY",
    subtitle: "SNAKE",
    info: "tssssssssss...",
    color: "text-neon-pink",
    neonClass: "neon-text-pink",
    coverImage: "/images/sneaky-cover.webp",
    galleryImages: [
      "/images/sneaky-1.webp",
      "/images/sneaky-2.webp",
      "/images/sneaky-3.webp",
      "/images/sneaky-4.webp",
      "/images/sneaky-5.webp",
      "/images/sneaky-6.webp",
    ],
    description:
      "The Neon Ghost haunts the urban landscape. Crafted from a proprietary phosphorescent polymer, it absorbs light during the day and emits a haunting pink radiance in total darkness.",
    year: "2024",
    material: "Resin",
    collection: "DESIGNER TOYS",
  },
  {
    id: 6,
    slug: "good-boy",
    title: "GOOD",
    subtitle: "BOY",
    info: "he obeys...",
    color: "text-neon-pink",
    neonClass: "neon-text-pink",
    coverImage: "/images/goodboy-cover.webp",
    galleryImages: [
      "/images/goodboy-1.webp",
      "/images/goodboy-2.webp",
      "/images/goodboy-3.webp",
      "/images/goodboy-4.webp",
      "/images/goodboy-5.webp",
      "/images/goodboy-6.webp",
      "/images/goodboy-7.webp",
      "/images/goodboy-8.webp",
    ],
    description:
      "The Neon Ghost haunts the urban landscape. Crafted from a proprietary phosphorescent polymer, it absorbs light during the day and emits a haunting pink radiance in total darkness.",
    year: "2024",
    material: "Resin",
    collection: "DESIGNER TOYS",
  },
  {
    id: 7,
    slug: "da-bomb",
    title: "DA",
    subtitle: "BOMB",
    info: "BOOOOOOOOOOOMMM!!!",
    color: "text-neon-pink",
    neonClass: "neon-text-pink",
    coverImage: "/images/dabomb-cover.webp",
    galleryImages: [
      "/images/dabomb-1.webp",
      "/images/dabomb-2.webp",
      "/images/dabomb-3.webp",
      "/images/dabomb-4.webp",
      "/images/dabomb-cover.webp",
    ],
    description:
      "The Neon Ghost haunts the urban landscape. Crafted from a proprietary phosphorescent polymer, it absorbs light during the day and emits a haunting pink radiance in total darkness.",
    year: "2024",
    material: "Resin",
    collection: "DESIGNER TOYS",
  },
  {
    id: 8,
    slug: "manduck",
    title: "MANDUCK",
    subtitle: " ",
    info: "IN ANOTHER FORM",
    color: "text-neon-pink",
    neonClass: "neon-text-pink",
    coverImage: "/images/manduck-cover.webp",
    galleryImages: [
      "/images/manduck-cover.webp",
      "/images/manduck-2.webp",
      "/images/manduck-3.webp",
      "/images/manduck-4.webp",
      "/images/manduck-5.webp",
      "/images/manduck-6.webp",
      "/images/manduck-7.webp",
      "/images/manduck-8.webp",
      "/images/manduck-9.webp",
    ],
    description:
      "The Neon Ghost haunts the urban landscape. Crafted from a proprietary phosphorescent polymer, it absorbs light during the day and emits a haunting pink radiance in total darkness.",
    year: "2025",
    material: "Resin",
    collection: "ACTION FIGURES",
  },
  {
    id: 9,
    slug: "real-friend",
    title: "REAL",
    subtitle: "FRIEND",
    info: "NEVER BE LONELY AGAIN...",
    color: "text-neon-pink",
    neonClass: "neon-text-pink",
    coverImage: "/images/realfriend-cover.webp",
    galleryImages: [
      "/images/realfriend-cover.webp",
      "/images/realfriend-2.webp",
      "/images/realfriend-3.webp",
      "/images/realfriend-4.webp",
      "/images/realfriend-5.webp",
      "/images/realfriend-6.webp",
      "/images/realfriend-7.webp",
      "/images/realfriend-8.webp",
      "/images/realfriend-9.webp",
    ],
    description:
      "The Neon Ghost haunts the urban landscape. Crafted from a proprietary phosphorescent polymer, it absorbs light during the day and emits a haunting pink radiance in total darkness.",
    year: "2025",
    material: "Resin",
    collection: "ACTION FIGURES",
  },
  /*

  collection: "CHARM", collection: "PRINTS", collection: "STICKERS",
  
  */
];
