export const NEON_COLORS = [
  { color: "text-neon-blue", hex: "#00f3ff", neonClass: "neon-text-blue" },
  { color: "text-neon-pink", hex: "#ff00ff", neonClass: "neon-text-pink" },
  { color: "text-neon-green", hex: "#00ff00", neonClass: "neon-text-green" },
  { color: "text-neon-yellow", hex: "#fff700", neonClass: "neon-text-yellow" },
  { color: "text-neon-royal", hex: "#4d4dff", neonClass: "neon-text-royal" },
  { color: "text-neon-coral", hex: "#ff4d4d", neonClass: "neon-text-coral" },
  //{ color: "text-neon-purple", hex: "#bc13fe", neonClass: "neon-text-purple" },
  { color: "text-neon-orange", hex: "#ff9100", neonClass: "neon-text-orange" },
  //{ color: "text-neon-lime", hex: "#a6ff00", neonClass: "neon-text-lime" },
  //{ color: "text-neon-violet", hex: "#8b00ff", neonClass: "neon-text-violet" },
  //{ color: "text-neon-amber", hex: "#ffcc00", neonClass: "neon-text-amber" },
];

export const getRandomNeonColor = () =>
  NEON_COLORS[Math.floor(Math.random() * NEON_COLORS.length)];

export const TOYS = [
  {
    id: 1,
    slug: "slave-duck",
    title: "SLAVE",
    subtitle: "DUCK",
    info: "whatever you say, sir",
    color: "text-neon-blue",
    neonClass: "neon-text-blue",
    coverImage: "/images/slaveduck-cover.webp",
    galleryImages: [
      "/images/slaveduck-1.webp",
      "/images/slaveduck-2.webp",
      "/images/slaveduck-3.webp",
      "/images/slaveduck-4.webp",
    ],
    description:
      "This piece takes the familiar rubber duck silhouette and wraps it in high-contrast black leather aesthetics and industrial hardware. It's a sharp, yet underground twist on nostalgia that definitely isn't playing by the rules.",
    year: "2023",
    material: "Resin",
    editioninfo: "LIMITED EDITION",
    edition: "12 PIECES, 1 AVAILABLE",
    collection: "DESIGNER TOYS",
  },
  {
    id: 2,
    slug: "thekiss",
    title: "THE",
    subtitle: "KISS",
    info: "feel the heat...",
    color: "text-neon-pink",
    neonClass: "neon-text-pink",
    coverImage: "/images/kiss-2.webp",
    galleryImages: [
      "/images/kiss-2.webp",
      "/images/kiss-3.webp",
      "/images/kiss-4.webp",
      "/images/kiss-5.webp",
      "/images/kiss-6.webp",
      "/images/kiss-7.webp",
      "/images/kiss-cover.webp",
    ],
    description:
      "A tribute to retro-glam. The massive, sculpted hair and the heart-shaped kiss suspended in mid-air create a permanent state of flirtation. It's a bold, colorful piece that feels like a vintage pin-up poster stepped out into three dimensions.",
    year: "2023",
    material: "Resin",
    editioninfo: "LIMITED EDITION",
    edition: "5 PIECES, SOLD OUT",
    collection: "DESIGNER TOYS",
  },
  {
    id: 3,
    slug: "zureyder",
    title: "ZÜREYDER",
    subtitle: " ",
    info: "an imagnary friend to the earth",
    color: "text-neon-pink",
    neonClass: "neon-text-pink",
    coverImage: "/images/zureyder-cover.webp",
    galleryImages: [
      "/images/zureyder-1.webp",
      "/images/zureyder-2.webp",
      "/images/zureyder-3.webp",
      "/images/zureyder-4.webp",
      "/images/zureyder-5.webp",
      "/images/zureyder-6.webp",
    ],
    description:
      "Part tank, part beast, part industrial accident. The grimy, weathered paint job and triple-pipe exhaust give it the look of a machine that's been drifting through the wasteland for years. It's a heavy, mechanical sculpt with a massive profile and a lot of grit.",
    year: "2024",
    material: "Resin",
    editioninfo: "LIMITED EDITION",
    edition: "5 PIECES, SOLD OUT",
    collection: "DESIGNER TOYS",
  },
  {
    id: 4,
    slug: "mr-giraffe",
    title: "MISTER",
    subtitle: "GIRAFFE",
    info: "have a nice daaaay!",
    color: "text-neon-pink",
    neonClass: "neon-text-pink",
    coverImage: "/images/mrgiraffe-cover.webp",
    galleryImages: [
      "/images/mrgiraffe-1.webp",
      "/images/mrgiraffe-2.webp",
      "/images/mrgiraffe-3.webp",
      "/images/mrgiraffe-4.webp",
      "/images/mrgiraffe-5.webp",
      "/images/mrgiraffe-6.webp",
    ],
    description:
      "The physical embodiment of a long weekend. With a sweatband on a head literally over the clouds, a chocolate dip icecream cone in hand, and cool slides on his white socks, this giraffe is operating at a level of relaxation most can only hope for. It's a top-heavy, absurd slice of peak leisure.",
    year: "2024",
    material: "Resin",
    editioninfo: "LIMITED EDITION",
    edition: "6 PIECES, 3 AVAILABLE",
    collection: "DESIGNER TOYS",
  },
  {
    id: 5,
    slug: "sneaky-snake",
    title: "SNEAKY",
    subtitle: "SNAKE",
    info: "tssssssssss...",
    color: "text-neon-pink",
    neonClass: "neon-text-pink",
    coverImage: "/images/sneaky-cover.webp",
    galleryImages: [
      "/images/sneaky-1.webp",
      "/images/sneaky-2.webp",
      "/images/sneaky-3.webp",
      "/images/sneaky-4.webp",
      "/images/sneaky-5.webp",
      "/images/sneaky-6.webp",
    ],
    description:
      "A high-visibility warning sign disguised as a collector's piece or some Saturday morning villainy with a sharp edge. The jagged blade held in the mouth and the severed tail bone adds a bit of gruesome humor to the mix. It's a colorful, dangerous-looking reptile that's clearly up to something no good.",
    year: "2024",
    material: "Resin",
    editioninfo: "LIMITED EDITION",
    edition: "10 PIECES, 7 AVAILABLE",
    collection: "DESIGNER TOYS",
  },
  {
    id: 6,
    slug: "good-boy",
    title: "GOOD",
    subtitle: "BOY",
    info: "he obeys...",
    color: "text-neon-pink",
    neonClass: "neon-text-pink",
    coverImage: "/images/goodboy-cover.webp",
    galleryImages: [
      "/images/goodboy-1.webp",
      "/images/goodboy-2.webp",
      "/images/goodboy-3.webp",
      "/images/goodboy-4.webp",
      "/images/goodboy-5.webp",
      "/images/goodboy-6.webp",
      "/images/goodboy-7.webp",
      "/images/goodboy-8.webp",
    ],
    description:
      "Luxury obedience with a dark edge. That massive industrial zipper isn't just a great tactile detail—it makes you wonder if these pups are actually just a high-fashion disguise for something else entirely. A silent, weighted companion for a modern collection.",
    year: "2024",
    material: "Resin",
    editioninfo: "LIMITED EDITION",
    edition: "14 PIECES, 5 AVAILABLE.",
    collection: "DESIGNER TOYS",
  },
  {
    id: 7,
    slug: "da-bomb",
    title: "DA",
    subtitle: "BOMB",
    info: "BOOOOOOOOOOOMMM!!!",
    color: "text-neon-pink",
    neonClass: "neon-text-pink",
    coverImage: "/images/dabomb-cover.webp",
    galleryImages: [
      "/images/dabomb-1.webp",
      "/images/dabomb-2.webp",
      "/images/dabomb-3.webp",
      "/images/dabomb-4.webp",
      "/images/dabomb-cover.webp",
    ],
    description:
      "A high-energy hazard with a very short fuse. Between the classic red shades and the oversized sneakers, this figure carries the chaotic energy of someone who wasn't invited but showed up anyway. It's built for a shelf that needs a literal explosion of personality.",
    year: "2024",
    material: "Resin",
    editioninfo: "LIMITED EDITION",
    edition: "1 of 1, SOLD OUT",
    collection: "DESIGNER TOYS",
  },
  {
    id: 8,
    slug: "manduck",
    title: "MANDUCK",
    subtitle: " ",
    info: "SAME OLD DUCK, ANOTHER FORM...",
    color: "text-neon-pink",
    neonClass: "neon-text-pink",
    coverImage: "/images/manduck-cover.webp",
    galleryImages: [
      "/images/manduck-cover.webp",
      "/images/manduck-2.webp",
      "/images/manduck-3.webp",
      "/images/manduck-4.webp",
      "/images/manduck-5.webp",
      "/images/manduck-6.webp",
      "/images/manduck-7.webp",
      "/images/manduck-8.webp",
      "/images/manduck-9.webp",
    ],
    description:
      "The counterpart to the chaos. Cloaked in a full-body leather-style harness with a ball gag detail, this duck swaps innocence for a strictly underground aesthetic. The shiny black gear against the bright yellow skin makes for an aggressive, unmistakable profile.",
    year: "2025",
    material: "Resin",
    editioninfo: "LIMITED EDITION",
    edition: "13 PIECES, 2 AVAILBLE",
    collection: "ACTION FIGURES",
  },
  {
    id: 9,
    slug: "real-friend",
    title: "REAL",
    subtitle: "FRIEND",
    info: "NEVER BE LONELY AGAIN...",
    color: "text-neon-pink",
    neonClass: "neon-text-pink",
    coverImage: "/images/realfriend-cover.webp",
    galleryImages: [
      "/images/realfriend-cover.webp",
      "/images/realfriend-2.webp",
      "/images/realfriend-3.webp",
      "/images/realfriend-4.webp",
      "/images/realfriend-5.webp",
      "/images/realfriend-6.webp",
      "/images/realfriend-7.webp",
      "/images/realfriend-8.webp",
      "/images/realfriend-9.webp",
    ],
    description:
      "A raw, unpolished take on companionship. She looks like an artifact from a fever dream that someone decided to materialize in a garage workshop, with a presence that feels more like a degenerate thought than a factory product. She doesn't try to be pretty; she just tries to be real.",
    year: "2025",
    material: "Resin",
    editioninfo: "LIMITED EDITION",
    edition: "11 PIECES, SOLD OUT",
    collection: "ACTION FIGURES",
  },
  {
    id: 10,
    slug: "zureyder-hotrod",
    title: "ZÜREYDER",
    subtitle: "HOT ROD KIT",
    info: "Upgrade parts kit",
    color: "text-neon-pink",
    neonClass: "neon-text-pink",
    coverImage: "/images/zureyder-hotrod-01.webp",
    galleryImages: [
      "/images/zureyder-hotrod-01.webp",
      "/images/zureyder-hotrod-02.webp",
      "/images/zureyder-hotrod-03.webp",
      "/images/zureyder-hotrod-04.webp",
      "/images/zureyder-hotrod-05.webp",
      "/images/zureyder-hotrod-06.webp",
      "/images/zureyder-hotrod-07.webp",
      "/images/zureyder-hotrod-08.webp",
      "/images/zureyder-hotrod-09.webp",
      "/images/zureyder-hotrod-10.webp",
      "/images/zureyder-hotrod-11.webp",
      "/images/zureyder-hotrod-12.webp",
      "/images/zureyder-hotrod-13.webp",
      "/images/zureyder-hotrod-14.webp",
      "/images/zureyder-hotrod-turntable.webp",
    ],
    description:
      "The 'Hot Rod' upgrade kit transforms Zureyder from a sluggish wasteland wanderer into a high-octane marauder. Swapping artillery for exposed chrome and aggressive, over-sized exhaust pipes, this kit injects a sense of reckless speed into the massive silhouette. It maintains that signature industrial grit while adding the unmistakable, scorched-metal aesthetic of a machine built for the drag strips of the apocalypse.",
    year: "2025",
    material: "Resin",
    editioninfo: "LIMITED EDITION",
    edition: "1 of 1, SOLD OUT",
    collection: "DESIGNER TOYS",
  },
  {
    id: 11,
    slug: "robits",
    title: "ROBITS",
    subtitle: "PACK-1",
    info: "Sticker Pack",
    color: "text-neon-pink",
    neonClass: "neon-text-pink",
    coverImage: "/images/robits-01.webp",
    galleryImages: [
      "/images/robits-01.webp",
      "/images/robits-02.webp",
      "/images/robits-03.webp",
      "/images/robits-04.webp",
      "/images/robits-05.webp",
    ],
    description:
      "Robits is a curated sticker collection that reimagines the most iconic robots of 90s cinema and TV through a fresh, stylized lens. Each piece captures the soul of these legendary machines in a compact form — blending nostalgic retro-cartoon aesthetics with a distinct three-quarter perspective. From towering mechs to galactic tin men, Robits transforms heavy-duty metal into a minimalist, collectible art style perfect for any surface.",
    year: "2025",
    material: "Holographic Sticker Paper",
    editioninfo: "OPEN EDITION",
    edition: "-",
    collection: "STICKER PACKS",
  },
  /*

  collection: "CHARM", collection: "PRINTS", collection: "STICKERS",
  
  */
];
