export const NEON_COLORS = [
  { color: "text-neon-blue", hex: "#00f3ff", neonClass: "neon-text-blue" },
  { color: "text-neon-pink", hex: "#ff00ff", neonClass: "neon-text-pink" },
  { color: "text-neon-green", hex: "#00ff00", neonClass: "neon-text-green" },
  { color: "text-neon-yellow", hex: "#fff700", neonClass: "neon-text-yellow" },
  { color: "text-neon-royal", hex: "#4d4dff", neonClass: "neon-text-royal" },
  { color: "text-neon-coral", hex: "#ff4d4d", neonClass: "neon-text-coral" },
  { color: "text-neon-purple", hex: "#bc13fe", neonClass: "neon-text-purple" },
];

export const getRandomNeonColor = () =>
  NEON_COLORS[Math.floor(Math.random() * NEON_COLORS.length)];

export const TOYS = [
  {
    id: 1,
    slug: "slave-duck",
    title: "SLAVE",
    subtitle: "DUCK",
    info: "whatever you say sir",
    color: "text-neon-blue",
    neonClass: "neon-text-blue",
    coverImage: "/images/slaveduck-cover.webp",
    galleryImages: [
      "/images/slaveduck-1.webp",
      "/images/slaveduck-2.webp",
      "/images/slaveduck-3.webp",
      "/images/slaveduck-4.webp",
    ],
    description:
      "A fusion of traditional Japanese aesthetics and high-tech materials. Cyber Mochi features a translucent shell with internal fiber-optic lighting that pulses with a rhythmic glow.",
    year: "2023",
    material: "Resin",
    collection: "TOYS",
  },
  {
    id: 2,
    slug: "thekiss",
    title: "THE",
    subtitle: "KISS",
    info: "feel it on your cheek...",
    color: "text-neon-pink",
    neonClass: "neon-text-pink",
    coverImage: "/images/kiss-1.webp",
    galleryImages: [
      "/images/kiss-1.webp",
      "/images/kiss-2.webp",
      "/images/kiss-3.webp",
      "/images/kiss-4.webp",
      "/images/kiss-5.webp",
      "/images/kiss-6.webp",
      "/images/kiss-7.webp",
    ],
    description:
      "The Neon Ghost haunts the urban landscape. Crafted from a proprietary phosphorescent polymer, it absorbs light during the day and emits a haunting pink radiance in total darkness.",
    year: "2023",
    material: "Resin",
    collection: "TOYS",
  },
  {
    id: 3,
    slug: "zureyder",
    title: "ZÜREYDER",
    subtitle: " ",
    info: "an imagnary friend to the earth",
    color: "text-neon-pink",
    neonClass: "neon-text-pink",
    coverImage: "/images/zureyder-cover.webp",
    galleryImages: [
      "/images/zureyder-1.webp",
      "/images/zureyder-2.webp",
      "/images/zureyder-3.webp",
      "/images/zureyder-4.webp",
      "/images/zureyder-5.webp",
      "/images/zureyder-6.webp",
    ],
    description:
      "The Neon Ghost haunts the urban landscape. Crafted from a proprietary phosphorescent polymer, it absorbs light during the day and emits a haunting pink radiance in total darkness.",
    year: "2024",
    material: "Resin",
    collection: "TOYS",
  },
  {
    id: 4,
    slug: "mr-giraffe",
    title: "MISTER",
    subtitle: "GIRAFFE",
    info: "have a nice day",
    color: "text-neon-pink",
    neonClass: "neon-text-pink",
    coverImage: "/images/mrgiraffe-cover.webp",
    galleryImages: [
      "/images/mrgiraffe-1.webp",
      "/images/mrgiraffe-2.webp",
      "/images/mrgiraffe-3.webp",
      "/images/mrgiraffe-4.webp",
      "/images/mrgiraffe-5.webp",
      "/images/mrgiraffe-6.webp",
    ],
    description:
      "The Neon Ghost haunts the urban landscape. Crafted from a proprietary phosphorescent polymer, it absorbs light during the day and emits a haunting pink radiance in total darkness.",
    year: "2024",
    material: "Resin",
    collection: "TOYS",
  },
  {
    id: 5,
    slug: "sneaky-snake",
    title: "SNEAKY",
    subtitle: "SNAKE",
    info: "tssssssssss",
    color: "text-neon-pink",
    neonClass: "neon-text-pink",
    coverImage: "/images/sneaky-cover.webp",
    galleryImages: [
      "/images/sneaky-1.webp",
      "/images/sneaky-2.webp",
      "/images/sneaky-3.webp",
      "/images/sneaky-4.webp",
      "/images/sneaky-5.webp",
      "/images/sneaky-6.webp",
    ],
    description:
      "The Neon Ghost haunts the urban landscape. Crafted from a proprietary phosphorescent polymer, it absorbs light during the day and emits a haunting pink radiance in total darkness.",
    year: "2024",
    material: "Resin",
    collection: "TOYS",
  },
  /*
  {
    id: 4,
    slug: "urban-samurai",
    title: "Urban",
    subtitle: "Samurai",
    info: "03 / Chrome Finish",
    color: "text-neon-green",
    neonClass: "neon-text-green",
    coverImage:
      "https://images.unsplash.com/photo-1608889175123-8ee362201f81?q=80&w=1920&auto=format&fit=crop",
    galleryImages: [
      "https://images.unsplash.com/photo-1608889175123-8ee362201f81?q=80&w=1920&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1589254065878-42c9da997008?q=80&w=1920&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1531693251400-38df35776dc7?q=80&w=1920&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1612036782180-6f0b6cd846fe?q=80&w=1920&auto=format&fit=crop",
    ],
    description:
      "A modern warrior for the concrete jungle. The Urban Samurai is finished in a high-gloss emerald chrome that reflects the neon lights of the city. Comes with a detachable katana.",
    year: "2026",
    material: "Chrome-Plated Vinyl",
    collection: "CHARM",
  },
  {
    id: 5,
    slug: "tech-oni",
    title: "Tech",
    subtitle: "Oni",
    info: "04 / Carbon Fiber",
    color: "text-neon-yellow",
    neonClass: "neon-text-yellow",
    coverImage:
      "https://images.unsplash.com/photo-1612036782180-6f0b6cd846fe?q=80&w=1920&auto=format&fit=crop",
    galleryImages: [
      "https://images.unsplash.com/photo-1612036782180-6f0b6cd846fe?q=80&w=1920&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1550745165-9bc0b252726f?q=80&w=1920&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1544005313-94ddf0286df2?q=80&w=1920&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1534447677768-be436bb09401?q=80&w=1920&auto=format&fit=crop",
    ],
    description:
      "Inspired by ancient folklore and modern engineering. The Tech Oni features carbon fiber accents and a matte black finish, embodying a silent but powerful presence.",
    year: "2026",
    material: "Matte Vinyl & Carbon Fiber",
    collection: "PRINT",
  },
  {
    id: 6,
    slug: "royal-void",
    title: "Royal",
    subtitle: "Void",
    info: "05 / Deep Blue",
    color: "text-neon-royal",
    neonClass: "neon-text-royal",
    coverImage:
      "https://images.unsplash.com/photo-1531693251400-38df35776dc7?q=80&w=1920&auto=format&fit=crop",
    galleryImages: [
      "https://images.unsplash.com/photo-1531693251400-38df35776dc7?q=80&w=1920&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1518443855757-dfadac7101ae?q=80&w=1920&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1558679908-541bcf1249ff?q=80&w=1920&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=1920&auto=format&fit=crop",
    ],
    description:
      "The Royal Void is a masterpiece of depth and color. Its deep blue finish seems to swallow light, creating an illusion of infinite space within its compact form.",
    year: "2026",
    material: "High-Density Pigmented Resin",
    collection: "PRINT",
  },
  {
    id: 7,
    slug: "coral-pulse",
    title: "Coral",
    subtitle: "Pulse",
    info: "06 / Bio-Lume",
    color: "text-neon-coral",
    neonClass: "neon-text-coral",
    coverImage:
      "https://images.unsplash.com/photo-1589254065878-42c9da997008?q=80&w=1920&auto=format&fit=crop",
    galleryImages: [
      "https://images.unsplash.com/photo-1589254065878-42c9da997008?q=80&w=1920&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1544005313-94ddf0286df2?q=80&w=1920&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1566576721346-d4a3b4eaeb55?q=80&w=1920&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1614850523296-d8c1af93d400?q=80&w=1920&auto=format&fit=crop",
    ],
    description:
      "Inspired by deep-sea bioluminescence. The Coral Pulse features a vibrant warm-red tone that shifts in intensity depending on the viewing angle.",
    year: "2026",
    material: "Iridescent Soft Vinyl",
    collection: "PRINT",
  },
  {
    id: 8,
    slug: "purple-haze",
    title: "Purple",
    subtitle: "Haze",
    info: "07 / Nebula",
    color: "text-neon-purple",
    neonClass: "neon-text-purple",
    coverImage:
      "https://images.unsplash.com/photo-1550684848-fac1c5b4e853?q=80&w=1920&auto=format&fit=crop",
    galleryImages: [
      "https://images.unsplash.com/photo-1550684848-fac1c5b4e853?q=80&w=1920&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1534447677768-be436bb09401?q=80&w=1920&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1612036782180-6f0b6cd846fe?q=80&w=1920&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1550745165-9bc0b252726f?q=80&w=1920&auto=format&fit=crop",
    ],
    description:
      "A cosmic traveler captured in a toy. Purple Haze features a swirling nebula-like pattern within its translucent violet body, making each piece unique.",
    year: "2026",
    material: "Swirled Translucent Resin",
    collection: "PRINT",
  },
  {
    id: 9,
    slug: "retro-glitch",
    title: "Retro",
    subtitle: "Glitch",
    info: "08 / Analog Era",
    color: "text-neon-green",
    neonClass: "neon-text-green",
    coverImage:
      "https://images.unsplash.com/photo-1550745165-9bc0b252726f?q=80&w=1920&auto=format&fit=crop",
    galleryImages: [
      "https://images.unsplash.com/photo-1550745165-9bc0b252726f?q=80&w=1920&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1550684848-fac1c5b4e853?q=80&w=1920&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1544005313-94ddf0286df2?q=80&w=1920&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1614850523296-d8c1af93d400?q=80&w=1920&auto=format&fit=crop",
    ],
    description:
      "A tribute to the early days of computing. Retro Glitch features a pixelated texture and a vibrant green glow reminiscent of vintage CRT monitors.",
    year: "2025",
    material: "Textured ABS Plastic",
    collection: "PRINT",
  },
  {
    id: 10,
    slug: "solar-flare",
    title: "Solar",
    subtitle: "Flare",
    info: "09 / Heat Wave",
    color: "text-neon-yellow",
    neonClass: "neon-text-yellow",
    coverImage:
      "https://images.unsplash.com/photo-1544005313-94ddf0286df2?q=80&w=1920&auto=format&fit=crop",
    galleryImages: [
      "https://images.unsplash.com/photo-1544005313-94ddf0286df2?q=80&w=1920&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1589254065878-42c9da997008?q=80&w=1920&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1566576721346-d4a3b4eaeb55?q=80&w=1920&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1612036782180-6f0b6cd846fe?q=80&w=1920&auto=format&fit=crop",
    ],
    description:
      "Capturing the raw energy of the sun. Solar Flare is finished in a brilliant yellow that seems to radiate heat, with a surface that shimmers like a plasma field.",
    year: "2025",
    material: "Heat-Reactive Polymer",
    collection: "PRINT",
  },
  {
    id: 11,
    slug: "vapor-wave",
    title: "Vapor",
    subtitle: "Wave",
    info: "10 / Aesthetic",
    color: "text-neon-pink",
    neonClass: "neon-text-pink",
    coverImage:
      "https://images.unsplash.com/photo-1614850523296-d8c1af93d400?q=80&w=1920&auto=format&fit=crop",
    galleryImages: [
      "https://images.unsplash.com/photo-1614850523296-d8c1af93d400?q=80&w=1920&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1550684848-fac1c5b4e853?q=80&w=1920&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1534447677768-be436bb09401?q=80&w=1920&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1518443855757-dfadac7101ae?q=80&w=1920&auto=format&fit=crop",
    ],
    description:
      "Pure 80s nostalgia. Vapor Wave combines pastel pinks and purples with a smooth, aerodynamic form that feels like it belongs in a synthwave music video.",
    year: "2025",
    material: "Soft-Touch Matte Vinyl",
    collection: "PRINT",
  },
  {
    id: 12,
    slug: "deep-sea",
    title: "Deep",
    subtitle: "Sea",
    info: "11 / Abyss",
    color: "text-neon-blue",
    neonClass: "neon-text-blue",
    coverImage:
      "https://images.unsplash.com/photo-1518443855757-dfadac7101ae?q=80&w=1920&auto=format&fit=crop",
    galleryImages: [
      "https://images.unsplash.com/photo-1518443855757-dfadac7101ae?q=80&w=1920&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1531693251400-38df35776dc7?q=80&w=1920&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1558679908-541bcf1249ff?q=80&w=1920&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=1920&auto=format&fit=crop",
    ],
    description:
      "From the darkest depths of the ocean. Deep Sea features a bioluminescent blue core protected by a rugged, pressure-resistant outer shell.",
    year: "2025",
    material: "Reinforced Polycarbonate",
    collection: "PRINT",
  },
  {
    id: 13,
    slug: "acid-rain",
    title: "Acid",
    subtitle: "Rain",
    info: "12 / Toxic Glow",
    color: "text-neon-purple",
    neonClass: "neon-text-purple",
    coverImage:
      "https://images.unsplash.com/photo-1534447677768-be436bb09401?q=80&w=1920&auto=format&fit=crop",
    galleryImages: [
      "https://images.unsplash.com/photo-1534447677768-be436bb09401?q=80&w=1920&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1614850523296-d8c1af93d400?q=80&w=1920&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1550684848-fac1c5b4e853?q=80&w=1920&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1550745165-9bc0b252726f?q=80&w=1920&auto=format&fit=crop",
    ],
    description:
      "A warning from a dystopian future. Acid Rain features a striking purple glow that appears to drip down its surface, creating a toxic yet beautiful aesthetic.",
    year: "2025",
    material: "Drip-Cast Resin",
    collection: "STICKER",
  },
  */
];
