// api/toys.ts
const TOYS = [
  {
    id: 1,
    slug: "slave-duck",
    title: "SLAVE",
    subtitle: "DUCK",
    info: "whatever you say, sir",
    color: "text-neon-blue",
    neonClass: "neon-text-blue",
    coverImage: "/images/slave-duck-designer-toy-cover.webp",
    coverAlt:
      "Slave Duck luxury obedience handmade designer resin toy by Dirtcake Studio, featuring high-contrast black leather aesthetics and industrial hardware on a duck silhouette.",
    galleryImages: [
      "/images/slave-duck-designer-toy-1.webp",
      "/images/slave-duck-designer-toy-2.webp",
      "/images/slave-duck-designer-toy-3.webp",
      "/images/slave-duck-designer-toy-4.webp",
      "/images/slave-duck-designer-toy-cover.webp",
    ],
    galleryAlt: [
      "Frontal view of the Slave Duck handmade designer toy figure, a quirky and underground twist on nostalgia that wraps a familiar silhouette in black leather aesthetics.",
      "Rear view of the Slave Duck handmade designer toy highlighting the black leather finish and the industrial hardware that defines this underground resin art piece.",
      "Slave Duck handmade designer toy showcasing the packaging design, highlighting how the piece is wrapped in high-contrast aesthetics and industrial hardware.",
      "Slave Duck handmade designer toy shown in its box, featuring a silhouette that takes a familiar duck form and gives it a cute, underground, and quirky twist.",
      "Slave Duck handmade designer luxury obedience toy figure by Dirtcake Studio, a familiar silhouette in black leather aesthetics. #luxuryobedience",
    ],
    description:
      "This piece takes the familiar rubber duck silhouette and wraps it in high-contrast black leather aesthetics and industrial hardware. It's a sharp, yet underground twist on nostalgia that definitely isn't playing by the rules.",
    year: "2023",
    material: "Resin",
    editioninfo: "LIMITED EDITION",
    edition: "12 PIECES, 1 AVAILABLE",
    collection: "designer toy",
    tweetHooks: [
      "this duck definitely has a backstory...",
      "i dont trust this duck at all :)",
      "🫪 something is off about this duck",
      "innocence meets naughty?",
    ],
    tweetCTA: ["be honest would you display this?", "yes or no?"],
  },
  {
    id: 2,
    slug: "the-kiss",
    title: "THE",
    subtitle: "KISS",
    info: "feel the heat...",
    color: "text-neon-pink",
    neonClass: "neon-text-pink",
    coverImage: "/images/kiss-designer-toy-figure-sculpture-2.webp",
    coverAlt:
      "The Kiss handmade designer resin toy by Dirtcake Studio, a tribute to retro-glam with massive sculpted hair and a heart-shaped kiss suspended in mid-air for flirtation.",
    galleryImages: [
      "/images/kiss-designer-toy-figure-sculpture-2.webp",
      "/images/kiss-designer-toy-figure-sculpture-1.webp",
      "/images/kiss-designer-toy-figure-sculpture-3.webp",
      "/images/kiss-designer-toy-figure-sculpture-4.webp",
      "/images/kiss-designer-toy-figure-sculpture-5.webp",
      "/images/kiss-designer-toy-figure-sculpture-6.webp",
      "/images/kiss-designer-toy-figure-sculpture-cover.webp",
    ],
    galleryAlt: [
      "Studio portrait of The Kiss handmade designer toy, a bold and colorful resin piece that feels like a vintage pin-up poster stepped out into three physical dimensions.",
      "Front view photo of The Kiss handmade designer toy, emphasizing the massive sculpted hair and the heart-shaped kiss that creates a permanent state of flirtation.",
      "Close-up of the heart-shaped kiss detail on the handmade designer toy figure, a bold and colorful element suspended in mid-air as a tribute to retro-glam.",
      "Rear view of The Kiss handmade resin sculpture, showcasing the natural flow of this bold and colorful retro-glam designer toy piece.",
      "High-angle shot of The Kiss handmade figure, a bold, colorful resin sculpture featuring massive sculpted hair and a heart-shaped kiss detail suspended in mid-air.",
      "Detail of the back of the handmade toy focusing on the massive sculpted hair, a key feature of this bold resin piece that feels like a three-dimensional pin-up poster.",
      "Low angle photo portrait of The Kiss retro-glam handmade designer toy figure by Dirtcake Studio, showing the massive sculpted hair and heart-shaped kiss in mid-air.",
    ],
    description:
      "A tribute to retro-glam. The massive, sculpted hair and the heart-shaped kiss suspended in mid-air create a permanent state of flirtation. It's a bold, colorful piece that feels like a vintage pin-up poster stepped out into three dimensions.",
    year: "2023",
    material: "Resin",
    editioninfo: "LIMITED EDITION",
    edition: "5 PIECES, SOLD OUT",
    collection: "designer toy",
    tweetHooks: [
      "this one never stops flirting ✌️",
      "caught mid kiss forever...",
      "too much or just enough?",
      "YES",
    ],
    tweetCTA: ["would you put this on your shelf?"],
  },
  {
    id: 3,
    slug: "zureyder",
    title: "ZÜREYDER",
    subtitle: " ",
    info: "an imagnary friend to the earth",
    color: "text-neon-pink",
    neonClass: "neon-text-pink",
    coverImage: "/images/zureyder-designer-toy-cover.webp",
    coverAlt:
      "Zureyder tank beast handmade designer resin toy by Dirtcake Studio, part tank and part beast with a grimy, weathered paint job and triple-pipe exhaust for a gritty look.",
    galleryImages: [
      "/images/zureyder-designer-toy-1.webp",
      "/images/zureyder-designer-toy-2.webp",
      "/images/zureyder-designer-toy-3.webp",
      "/images/zureyder-designer-toy-4.webp",
      "/images/zureyder-designer-toy-5.webp",
      "/images/zureyder-designer-toy-6.webp",
      "/images/zureyder-designer-toy-cover.webp",
    ],
    galleryAlt: [
      "Zureyder tank beast handmade designer toy figure and magnet attachable parts, looking like a heavy mechanical sculpt that has been drifting through the wasteland.",
      "Rear view of the mechanical beast Zureyder, highlighting the triple-pipe exhaust and the grimy, weathered paint job of this heavy industrial handmade resin sculpture.",
      "Detail of the Zureyder handmade figure head, showcasing the mechanical beast features and the industrial grit of the weathered paint on this heavy wasteland-style sculpt.",
      "Detail of the magnet attachable toy rocket launcher part, an industrial hardware component of the Zureyder tank beast mechanical handmade designer toy figure.",
      "Backside detail view of the mechanical beast Zureyder, focusing on the industrial grit, grimy weathered paint, and the heavy profile of the handmade wasteland machine.",
      "Frontside detail of the Zureyder tank beast handmade designer toy showing industrial grit and weathered paint on a heavy mechanical sculpt with a massive profile.",
      "Zureyder tank beast handmade designer toy by Dirtcake Studio, a heavy mechanical sculpt featuring industrial grit, a weathered paint job, and triple-pipe exhaust detail.",
    ],
    description:
      "Part tank, part beast, part industrial accident. The grimy, weathered paint job and triple-pipe exhaust give it the look of a machine that's been drifting through the wasteland for years. It's a heavy, mechanical sculpt with a massive profile and a lot of grit.",
    year: "2024",
    material: "Resin",
    editioninfo: "LIMITED EDITION",
    edition: "5 PIECES, SOLD OUT",
    collection: "designer toy",
    tweetHooks: [
      "this thing survived something :)",
      "not built for peace...",
      "found this in the wasteland, brought it home.",
      "what kind of giraffe needs a tank anyway...",
    ],
    tweetCTA: ["what would you name it?"],
  },
  {
    id: 4,
    slug: "mr-giraffe",
    title: "MISTER",
    subtitle: "GIRAFFE",
    info: "have a nice daaaay!",
    color: "text-neon-pink",
    neonClass: "neon-text-pink",
    coverImage: "/images/mr-giraffe-designer-toy-cover.webp",
    coverAlt:
      "Mister Giraffe handmade designer resin toy by Dirtcake Studio, featuring a sweatband, a head over the clouds, a chocolate dip ice cream cone, and slides on white socks.",
    galleryImages: [
      "/images/mr-giraffe-designer-toy-1.webp",
      "/images/mr-giraffe-designer-toy-2.webp",
      "/images/mr-giraffe-designer-toy-3.webp",
      "/images/mr-giraffe-designer-toy-4.webp",
      "/images/mr-giraffe-designer-toy-5.webp",
      "/images/mr-giraffe-designer-toy-6.webp",
    ],
    galleryAlt: [
      "Mister Giraffe handmade designer toy with its packaging design box, showing the fun-filled leisure figure with a head over the clouds and a chocolate dip ice cream cone.",
      "Close-up of the Mister Giraffe head with a sweatband, representing a character with a head literally over the clouds operating at a high level of peak leisure.",
      "Mister Giraffe holding a chocolate dip ice cream cone, a detail of the leisure figure that serves as the physical embodiment of a long weekend.",
      "Side view of the Mister Giraffe handmade leisure designer toy figure, highlighting the tall profile and the character's relaxed stance in slides and socks.",
      "Close-up of the Mister Giraffe handmade designer toy wearing slides and white socks, a leisure-themed detail on this absurd slice of peak relaxation.",
      "Full body shot of Mister Giraffe by Dirtcake Studio, a handmade designer resin toy with a sweatband and ice cream cone that embodies the feeling of a long weekend.",
    ],
    description:
      "The physical embodiment of a long weekend. With a sweatband on a head literally over the clouds, a chocolate dip icecream cone in hand, and cool slides on his white socks, this giraffe is operating at a level of relaxation most can only hope for. It's a top-heavy, absurd slice of peak leisure.",
    year: "2024",
    material: "Resin",
    editioninfo: "LIMITED EDITION",
    edition: "6 PIECES, 3 AVAILABLE",
    collection: "designer toy",
    tweetHooks: [
      "he didnt ask to be this tall 😁",
      "living his best life honestly ✌️",
      "this is peak relaxation 🧿",
      "now I want icecream too",
    ],
    tweetCTA: ["mood or not?"],
  },
  {
    id: 5,
    slug: "sneaky-snake",
    title: "SNEAKY",
    subtitle: "SNAKE",
    info: "tssssssssss...",
    color: "text-neon-pink",
    neonClass: "neon-text-pink",
    coverImage: "/images/sneaky-snake-designer-toy-cover.webp",
    coverAlt:
      "Sneaky Snake handmade designer toy with a jagged blade in its mouth and packaging box by Dirtcake Studio, a colorful villain figure with a severed tail bone detail.",
    galleryImages: [
      "/images/sneaky-snake-designer-toy-1.webp",
      "/images/sneaky-snake-designer-toy-2.webp",
      "/images/sneaky-snake-designer-toy-3.webp",
      "/images/sneaky-snake-designer-toy-4.webp",
      "/images/sneaky-snake-designer-toy-5.webp",
      "/images/sneaky-snake-designer-toy-6.webp",
      "/images/sneaky-snake-designer-toy-cover.webp",
    ],
    galleryAlt: [
      "Sneaky Snake handmade designer toy featuring a jagged blade and severed tail bone, shown with its vibrant packaging box as a colorful and dangerous-looking reptile.",
      "Rear view of the coiled Sneaky Snake handmade sculpture, showing the form of this colorful reptile that carries the chaotic energy of Saturday morning villainy.",
      "Side view of the Sneaky Snake handmade villain figure in vibrant colors, capturing the mischievous expression and the jagged blade held in the reptile's mouth.",
      "High-angle close-up of the knife in the mouth of the Sneaky Snake, showing the jagged blade and the vibrant colors of this dangerous-looking handmade designer figure.",
      "Close-up of the severed tail bone detail on the Sneaky Snake, adding a bit of gruesome humor to this colorful and handmade mischievous Saturday morning villain toy.",
      "Glow-in-the-dark shot of the Sneaky Snake, showcasing how this colorful reptile and its jagged blade accessory appear when the lights are turned off.",
      "Low angle close-up of the knife in the mouth detail of the Sneaky Snake, a colorful and dangerous-looking villain figure handmade designer toy by Dirtcake Studio.",
    ],
    description:
      "A high-visibility warning sign disguised as a collector's piece or some Saturday morning villainy with a sharp edge. The jagged blade held in the mouth and the severed tail bone adds a bit of gruesome humor to the mix. It's a colorful, dangerous-looking reptile that's clearly up to something no good.",
    year: "2024",
    material: "Resin",
    editioninfo: "LIMITED EDITION",
    edition: "10 PIECES, 7 AVAILABLE",
    collection: "designer toy",
    tweetHooks: [
      "turn off the lights...",
      "this one behaves differently at night 😁",
      "something about this feels illegal 🤭",
      "TsssSSSSSsssSssSSsss 🐍",
    ],
    tweetCTA: ["pet or run?"],
  },
  {
    id: 6,
    slug: "good-boy",
    title: "GOOD",
    subtitle: "BOY",
    info: "he obeys...",
    color: "text-neon-pink",
    neonClass: "neon-text-pink",
    coverImage: "/images/goodboy-designer-toy-cover.webp",
    coverAlt:
      "Yellow, Black, Silver and Golden Good Boy handmade luxury obedience designer toys by Dirtcake Studio, featuring oversized industrial zipper details on weighted resin pups.",
    galleryImages: [
      "/images/goodboy-designer-toy-1.webp",
      "/images/goodboy-designer-toy-2.webp",
      "/images/goodboy-designer-toy-3.webp",
      "/images/goodboy-designer-toy-4.webp",
      "/images/goodboy-designer-toy-5.webp",
      "/images/goodboy-designer-toy-6.webp",
      "/images/goodboy-designer-toy-7.webp",
      "/images/goodboy-designer-toy-8.webp",
    ],
    galleryAlt: [
      "Portrait of the black Good Boy luxury obedience handmade designer toy and its packaging box, showcasing the luxury obedience figure and its massive industrial zipper detail.",
      "Frontal portrait of the black Good Boy handmade designer toy dog, showcasing the massive industrial zipper detail that gives this luxury obedience figure a dark edge.",
      "Rear view of the black Good Boy featuring the industrial zipper detail, a tactile element on this silent companion for a modern toy collection. #luxuryobedience",
      "Silver Good Boy handmade figure showing the luxury obedience aesthetic, featuring a resin body and an industrial zipper detail for a silent, modern profile.",
      "Golden Good Boy handmade figure showing the luxury obedience aesthetic, capturing the dark edge and tactile industrial zipper detail of this modern designer toy.",
      "Close-up of the oversized industrial zipper on a yellow Good Boy handmade figure, a tactile detail that highlights the luxury obedience theme and silent companion aesthetic.",
      "Glow-in-the-dark shot of the Yellow Good Boy toy, showing the handmade luxury obedience designer figure illuminated with a silent and modern neon-like glow.",
      "Group shot of Yellow, Black, Silver and Golden Good Boy handmade designer toys from various angles, showing the luxury obedience collection by Dirtcake Studio.",
    ],
    description:
      "Luxury obedience with a dark edge. That massive industrial zipper isn't just a great tactile detail—it makes you wonder if these pups are actually just a high-fashion disguise for something else entirely. A silent, weighted companion for a modern collection.",
    year: "2024",
    material: "Resin",
    editioninfo: "LIMITED EDITION",
    edition: "14 PIECES, 5 AVAILABLE.",
    collection: "designer toy",
    tweetHooks: [
      "he obeys but at what cost...",
      "he will behave.",
      "this one feels too quiet 😁",
      "still wouldnt leave him home alone :)",
    ],
    tweetCTA: ["would you pet it?"],
  },
  {
    id: 7,
    slug: "da-bomb",
    title: "DA",
    subtitle: "BOMB",
    info: "BOOOOOOOOOOOMMM!!!",
    color: "text-neon-pink",
    neonClass: "neon-text-pink",
    coverImage: "/images/dabomb-designer-toy-cover.webp",
    coverAlt:
      "Da Bomb handmade designer toy with red shades and sneakers by Dirtcake Studio, a high-energy hazard figure that brings a literal explosion of personality to the shelf.",
    galleryImages: [
      "/images/dabomb-designer-toy-1.webp",
      "/images/dabomb-designer-toy-2.webp",
      "/images/dabomb-designer-toy-3.webp",
      "/images/dabomb-designer-toy-4.webp",
      "/images/dabomb-designer-toy-cover.webp",
    ],
    galleryAlt: [
      "Da Bomb handmade designer toy featuring red shades and oversized sneakers, a limited edition resin figure that carries the chaotic energy of a potential hazard.",
      "Rear view of the Da Bomb handmade resin designer toy figure, showcasing the chaotic energy and sculptural details of the explosive pose and street-style sneakers.",
      "Da Bomb character captured in a chaotic energy pose, wearing classic red shades and oversized sneakers as a potential hazard with a very short fuse.",
      "Top-view high-angle close-up of the Da Bomb handmade figure, highlighting the sculptural details of the explosive and chaotic energy of this limited edition piece.",
      "Full frontal portrait of the Da Bomb limited edition handmade designer toy; a high-energy, potenatial hazard figure in red shades and sneakers from Dirtcake Studio.",
    ],
    description:
      "A high-energy hazard with a very short fuse. Between the classic red shades and the oversized sneakers, this figure carries the chaotic energy of someone who wasn't invited but showed up anyway. It's built for a shelf that needs a literal explosion of personality.",
    year: "2024",
    material: "Resin",
    editioninfo: "LIMITED EDITION",
    edition: "1 of 1, SOLD OUT",
    collection: "designer toy",
    tweetHooks: [
      "this one has a short fuse 💣",
      "definitely not safe for work :)",
      "who invited this guy?",
    ],
    tweetCTA: ["chaos or no?"],
  },
  {
    id: 8,
    slug: "manduck",
    title: "MANDUCK",
    subtitle: " ",
    info: "SAME OLD DUCK, ANOTHER FORM...",
    color: "text-neon-pink",
    neonClass: "neon-text-pink",
    coverImage: "/images/manduck-designer-action-figure-toy-cover.webp",
    coverAlt:
      "Manduck handmade designer action figure toy in full-body leather harness by Dirtcake Studio, featuring a ball gag detail and shiny black gear against bright yellow skin.",
    galleryImages: [
      "/images/manduck-designer-action-figure-toy-cover.webp",
      "/images/manduck-designer-action-figure-toy-2.webp",
      "/images/manduck-designer-action-figure-toy-3.webp",
      "/images/manduck-designer-action-figure-toy-4.webp",
      "/images/manduck-designer-action-figure-toy-5.webp",
      "/images/manduck-designer-action-figure-toy-6.webp",
      "/images/manduck-designer-action-figure-toy-7.webp",
      "/images/manduck-designer-action-figure-toy-8.webp",
      "/images/manduck-designer-action-figure-toy-9.webp",
    ],
    galleryAlt: [
      "Manduck handmade designer action figure toy in a leather harness, swapping innocence for an underground aesthetic with shiny black gear and aggressive details.",
      "Rear view of the Manduck handmade action figure, emphasizing the underground aesthetic and the detail of the shiny black leather-style gear against the muscular sculpt.",
      "Frontal view of the Manduck handmade designer action figure by Dirtcake Studio, showcasing the ball gag detail and the innocent but aggressive profile.",
      "Side profile of the Manduck handmade action figure showing the leather harness and ball gag detail, capturing the aggressive and unmistakable underground profile.",
      "Top-view close-up of the handmade designer toy and the ball gag detail, a key feature of its underground aesthetic and shiny black gear-focused design.",
      "Back view close-up of the Manduck handmade action figure with shiny black gear and yellow skin, highlighting the high-contrast gear against the muscular profile of the sculpt.",
      "Detail view of the Manduck handmade designer toy leather pants, showcasing the textures of the shiny black gear on this underground-themed resin action figure.",
      "Detail of the front packaging design for the Manduck action figure blister pack, reflecting the underground aesthetic and aggressive theme of the figure.",
      "Detail of the back packaging design for the Manduck resin toy blister pack, featuring the industrial and underground aesthetic of the figure by Dirtcake Studio.",
    ],
    description:
      "The counterpart to the chaos. Cloaked in a full-body leather-style harness with a ball gag detail, this duck swaps innocence for a strictly underground aesthetic. The shiny black gear against the bright yellow skin makes for an aggressive, unmistakable profile.",
    year: "2025",
    material: "Resin",
    editioninfo: "LIMITED EDITION",
    edition: "13 PIECES, 2 AVAILBLE",
    collection: "action figure",
    tweetHooks: [
      "same duck different energy.",
      "this escalated qwackly 😁",
      "this is not for everyone 🤭",
      "are you a man or a duck?",
      "do you even lift?",
    ],
    tweetCTA: ["orders?"],
  },
  {
    id: 9,
    slug: "real-friend",
    title: "REAL",
    subtitle: "FRIEND",
    info: "NEVER BE LONELY AGAIN...",
    color: "text-neon-pink",
    neonClass: "neon-text-pink",
    coverImage: "/images/real-friend-designer-action-figure-toy-cover.webp",
    coverAlt:
      "Real Friend handmade action figure designer resin toy by Dirtcake Studio, a raw and unpolished companion that looks like an artifact from a dream materialized in resin.",
    galleryImages: [
      "/images/real-friend-designer-action-figure-toy-cover.webp",
      "/images/real-friend-designer-action-figure-toy-2.webp",
      "/images/real-friend-designer-action-figure-toy-3.webp",
      "/images/real-friend-designer-action-figure-toy-4.webp",
      "/images/real-friend-designer-action-figure-toy-5.webp",
      "/images/real-friend-designer-action-figure-toy-6.webp",
      "/images/real-friend-designer-action-figure-toy-7.webp",
      "/images/real-friend-designer-action-figure-toy-8.webp",
      "/images/real-friend-designer-action-figure-toy-9.webp",
    ],
    galleryAlt: [
      "Real Friend handmade action figure designer toy, a piece that doesn't try to be pretty but tries to be real, showcasing a raw garage-workshop aesthetic.",
      "Frontal view of the Real Friend handmade resin designer toy action figure, capturing the presence of an unpolished companion that looks like a raw artifact.",
      "Close-up of the frontal view details on the Real Friend handmade action figure, focusing on the raw aesthetics of this in-your-face designer toy.",
      "Detail of the frontal view on the Real Friend handmade resin toy, highlighting the material honesty and the raw aesthetic.",
      "Detailed view of the Real Friend handmade designer toy, emphasizing its raw presence and style that defines this companionship piece.",
      "Front packaging design of the Real Friend handmade action figure blister pack, presenting the raw aesthetics of the companion as a physical collector's product.",
      "Back of the packaging design for the Real Friend handmade action figure blister pack, featuring the raw aesthetic of this resin-manifested companion.",
      "The black version of the Real Friend designer toy shown with its packaging, maintaining the raw aesthetic of the original resin sculpture.",
      "Back view of the black version of the Real Friend designer toy packaging, a raw and unpolished artifact from a dream by Dirtcake Studio.",
    ],
    description:
      "A raw, unpolished take on companionship. She looks like an artifact from a fever dream that someone decided to materialize in a garage workshop, with a presence that feels more like a degenerate thought than a factory product. She doesn't try to be pretty; she just tries to be real.",
    year: "2025",
    material: "Resin",
    editioninfo: "LIMITED EDITION",
    edition: "11 PIECES, SOLD OUT",
    collection: "action figure",
    tweetHooks: [
      "never feel lonely again...",
      "this one feels too real 🤭",
      "not supposed to look like this :)",
      "no regrets...",
      "need a friend?",
    ],
    tweetCTA: ["display it or hide it?"],
  },
  {
    id: 10,
    slug: "zureyder-hotrod",
    title: "ZÜREYDER",
    subtitle: "HOT ROD KIT",
    info: "Upgrade parts kit",
    color: "text-neon-pink",
    neonClass: "neon-text-pink",
    coverImage: "/images/zureyder-hot-rod-upgrade-kit-toy-01.webp",
    coverAlt:
      "Zureyder Hot Rod handmade upgrade kit with chrome exhaust pipes by Dirtcake Studio, featuring exposed engine-style parts and a scorched-metal aesthetic for speed.",
    galleryImages: [
      "/images/zureyder-hot-rod-upgrade-kit-toy-01.webp",
      "/images/zureyder-hot-rod-upgrade-kit-toy-02.webp",
      "/images/zureyder-hot-rod-upgrade-kit-toy-03.webp",
      "/images/zureyder-hot-rod-upgrade-kit-toy-04.webp",
      "/images/zureyder-hot-rod-upgrade-kit-toy-05.webp",
      "/images/zureyder-hot-rod-upgrade-kit-toy-06.webp",
      "/images/zureyder-hot-rod-upgrade-kit-toy-07.webp",
      "/images/zureyder-hot-rod-upgrade-kit-toy-08.webp",
      "/images/zureyder-hot-rod-upgrade-kit-toy-09.webp",
      "/images/zureyder-hot-rod-upgrade-kit-toy-10.webp",
      "/images/zureyder-hot-rod-upgrade-kit-toy-11.webp",
      "/images/zureyder-hot-rod-upgrade-kit-toy-12.webp",
      "/images/zureyder-hot-rod-upgrade-kit-toy-13.webp",
      "/images/zureyder-hot-rod-upgrade-kit-toy-14.webp",
      "/images/zureyder-hot-rod-upgrade-kit-toy-turntable.webp",
    ],
    galleryAlt: [
      "Zureyder Hot Rod handmade upgrade kit featuring aggressive, over-sized chrome exhaust pipes designed to inject a sense of reckless speed into the Zureyder silhouette.",
      "Packaging design and handmade kit parts for the Zureyder Hot Rod, showcasing the scorched-metal aesthetic and industrial grit of the high-octane marauder transformation.",
      "Comparison photo of the back views showing the original Zureyder next to the version with Hot Rod handmade upgrade parts, highlighting the aggressive exhaust pipes.",
      "Hot Rod kit showing exposed engine-style handmade parts and the Zureyder resin toy, featuring the scorched-metal aesthetic of a machine built for the drag strips.",
      "Back view of the Zureyder designer toy figure with the Hot Rod handmade upgrade kit components installed, showing the aggressive chrome and oversized exhaust pipes.",
      "Back view of the Zureyder designer toy figure with the Hot Rod handmade upgrade kit components installed, showing the aggressive chrome and oversized exhaust pipes.",
      "Back view of the Zureyder designer toy figure with the Hot Rod handmade upgrade kit components installed, showing the aggressive chrome and oversized exhaust pipes.",
      "Back view of the Zureyder designer toy figure with the Hot Rod handmade upgrade kit components installed, showing the aggressive chrome and oversized exhaust pipes.",
      "Frontal side view of the Zureyder Hot Rod transformation, highlighting the high-octane marauder look with exposed chrome and industrial grit details.",
      "Detail of industrial grit on the Hot Rod upgrade kit handmade engine parts laid out for assembly, showcasing the scorched-metal aesthetic of the transformation.",
      "Close-up of the chrome finish on the Hot Rod handmade upgrade kit engine placed on the Zureyder toy, adding reckless speed and shine to the industrial silhouette.",
      "Close-up detail shot of the aggressive exhaust pipes on the Zureyder, featuring the oversized chrome and scorched-metal look of a wasteland marauder.",
      "Close-up shot of the winged backside of the aggressive exhaust pipes on Zureyder, highlighting the scorched-metal aesthetic and oversized industrial details.",
      "Zureyder original parts and Hot Rod kit parts laid out for assembly, showing the components needed to transform the beast into a high-octane marauder.",
      "3/4 view of the complete Zureyder Hot Rod, showcasing the high-octane transformation with chrome and scorched-metal aesthetics by Dirtcake Studio.",
    ],
    description:
      "The 'Hot Rod' upgrade kit transforms Zureyder from a sluggish wasteland wanderer into a high-octane marauder. Swapping artillery for exposed chrome and aggressive, over-sized exhaust pipes, this kit injects a sense of reckless speed into the massive silhouette. It maintains that signature industrial grit while adding the unmistakable, scorched-metal aesthetic of a machine built for the drag strips of the apocalypse.",
    year: "2025",
    material: "Resin",
    editioninfo: "LIMITED EDITION",
    edition: "1 of 1, SOLD OUT",
    collection: "designer toy",
    tweetHooks: [
      "not sure this is safe...",
      "we made it faster for no reason...",
      "this was a bad idea 😁",
      "now its actually dangerous 🔥",
    ],
    tweetCTA: ["worth the upgrade?"],
  },

  {
    id: 12,
    slug: "genie-figure",
    title: "GENIE",
    subtitle: "FIGURE",
    info: "Comissioned Work",
    color: "text-neon-pink",
    neonClass: "neon-text-pink",
    coverImage: "/images/genie-mascot-figure-commission-1.webp",
    coverAlt:
      "Genie handmade mascot figure commission by Dirtcake Studio, showing a frontal high-angle photo of the friendly mascot and its resin magic lamp and smoke accessory.",
    galleryImages: [
      "/images/genie-mascot-figure-commission-1.webp",
      "/images/genie-mascot-figure-commission-2.webp",
      "/images/genie-mascot-figure-commission-3.webp",
      "/images/genie-mascot-figure-commission-4.webp",
      "/images/genie-mascot-figure-commission-5.webp",
      "/images/genie-mascot-figure-commission-6.webp",
      "/images/genie-mascot-figure-commission-7.webp",
      "/images/genie-mascot-figure-commission-8.webp",
      "/images/genie-mascot-figure-commission-9.webp",
    ],
    galleryAlt: [
      "Geniehandmade  mascot figure commission by Dirtcake Studio, showing a frontal high-angle photo of the friendly mascot and its resin magic lamp and smoke accessory.",
      "Frontal shot of the Genie handmade mascot resin figure commission with magic lamp, a friendly physical manifestation of a tech startup's digital AI assistant hero.",
      "Side view photo of the Genie startup hero mascot handmade figure commission and magic lamp, bringing a digital AI assistant vision into the physical world.",
      "Frontal close-up of the Genie mascot handmade figure commission and magic lamp, showcasing the friendly design and the craft detail of the physical resin sculpture.",
      "Front left side photo of the Genie mascot handmade figure commission and magic lamp, highlighting the friendly and approachable design of the custom-sculpted hero.",
      "Front right side close-up of the Genie mascot handmade figure commission, showing the magic lamp and the smoke accessory detail of the physical startup hero mascot.",
      "Detail of the resin magic lamp and smoke accessory from the Genie mascot handmade figure commission, bridging the gap between digital vision and physical craft.",
      "Close-up photo of the resin magic lamp and smoke accessory detail, with the Genie mascot handmade figure visible in the background of this custom commission work.",
      "Close-up of the resin smoke accessory for the Genie mascot handmade figure commission, representing the physical face of an AI assistant platform by Dirtcake Studio.",
    ],
    description:
      "We teamed up with a tech startup to bring their digital vision into the physical world. This custom-sculpted mascot serves as the face of their AI assistant platform, bridging the gap between cutting-edge technology and friendly, approachable design.",
    year: "2025",
    material: "Resin",
    editioninfo: "COMMISSION WORK",
    edition: "Not For Sale",
    collection: "commission",
    tweetHooks: [
      "wish granted but not exactly 😁",
      "this came out of a lamp :)",
      "would you trust this genie?",
    ],
    tweetCTA: ["what would you wish for?"],
  },
];

export default function handler(req: any, res: any) {
  try {
    const absoluteToys = TOYS.map((toy: any) => ({
      ...toy,
      coverImage: `https://www.dirtcakestudio.com${toy.coverImage}`,
      galleryImages: toy.galleryImages.map(
        (img: string) => `https://www.dirtcakestudio.com${img}`,
      ),
    }));

    res.setHeader("Access-Control-Allow-Origin", "*");
    res.setHeader("Content-Type", "application/json");
    return res.status(200).json(absoluteToys);
  } catch (error) {
    return res.status(500).json({ error: "Failed to render toys" });
  }
}
